name: movieland
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

# SDK sınırı en üstte ve bu hizada olmalı
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Klasör yapına (assets/images/Moviealand_logo.png) tam uyumlu hale getirildi
  assets:
    - assets/images/Moviealand_logo.png